sales/urls.py
from django.urls import path

from . import views

app_name = 'sales'
urlpatterns = [
        # Index
        path('', views.index, name='index'),
        # Sales
        path('sale/add/', views.SaleCreateView.as_view(), name='sale-create'),
        path('sale/<slug:slug>/view/', views.SaleDetailView.as_view(), name='sale-detail'),
        path('sale/<uuid:pk>/manage/', views.SaleManageView.as_view(), name='sale-manage'),
        path('sale/<uuid:pk>/update/', views.SaleUpdateView.as_view(), name='sale-update'),
        path('sale/<uuid:pk>/delete/', views.SaleDeleteView.as_view(), name='sale-delete'),
        # Items
        path('sale/<uuid:sale_id>/item/add/', views.ItemCreateView.as_view(), name='item-create'),
        path('item/<slug:slug>/view/', views.ItemDetailView.as_view(), name='item-detail'),
        path('item/<uuid:pk>/manage/', views.ItemManageView.as_view(), name='item-manage'),
        path('item/<uuid:pk>/update/', views.ItemUpdateView.as_view(), name='item-update'),
        path('item/<uuid:pk>/delete/', views.ItemDeleteView.as_view(), name='item-delete'),
        # Images
        path('item/<uuid:item_id>/image/add/', views.ItemImageCreateView.as_view(), name='image-create'),
        path('image/<uuid:pk>/update/', views.ItemImageUpdateView.as_view(), name='image-update'),
        path('image/<uuid:pk>/delete/', views.ItemImageDeleteView.as_view(), name='image-delete'),
]

sales/models.py
import uuid

from django.core.validators import MinLengthValidator, MinValueValidator
from django.db import models
from django.db.models import CheckConstraint, Q
from django.db.models.functions import Length
from django.utils.text import slugify
from django.urls import reverse
from sorl.thumbnail import ImageField

class AbstractUUIDMixin(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    @property
    def pk_s(self):
        return str(self.pk)

    class Meta:
        abstract = True

models.CharField.register_lookup(Length)

class AbstractNamedUUIDMixin(AbstractUUIDMixin):
    slug = models.SlugField(unique=True, editable=False)
    name = models.CharField(max_length=50)

    class Meta:
        abstract = True

        constraints = [
            models.CheckConstraint(
                check=Q(name__length__gte=1),
                name="%(app_label)s_%(class)s_name_length",
            )
        ]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        """Saves a unique slug for new objects."""
        if self.slug == '':
            # Get base slug name
            slug = slugify(self.name)

            # Update if already exists
            new_slug = slug
            num = 1
            while self.__class__.objects.filter(slug=new_slug).exists():
                new_slug = f"{slug}-{num}"
                num += 1

            # Finally, set it
            self.slug = new_slug

        super().save(*args, **kwargs)

class Sale(AbstractNamedUUIDMixin):
    created = models.DateTimeField(auto_now_add=True)


    def item_count(self):
        """Returns the number of items in the sale."""
        return self.items.count()

    def get_absolute_url(self):
        return reverse('sales:sale-manage', kwargs={'pk': self.pk})

class Item(AbstractNamedUUIDMixin):
    sale = models.ForeignKey('Sale', on_delete=models.CASCADE, related_name='items')
    price = models.DecimalField(max_digits=7, decimal_places=2, default=0.00, validators=[MinValueValidator(0.0, 'Price cannot be less than zero.')])
    description = models.TextField(blank=True)

    class Meta:
        constraints = AbstractNamedUUIDMixin.Meta.constraints + [CheckConstraint(check=Q(price__gte=0.00), name="item_price_minimum")]

    def image_count(self):
        """Returns the number of images in the sale."""
        return self.images.count()

    def get_absolute_url(self):
        return reverse('sales:item-manage', kwargs={'pk': self.pk})


class ItemImage(AbstractUUIDMixin):
    item = models.ForeignKey('Item', on_delete=models.CASCADE, related_name='images')
    image = ImageField(upload_to="images/")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'item="{self.item}" path="{self.image.name}"'

sales/forms.py
from django.forms import ModelForm

from .models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'price', 'description')

sales/views.py
from django.forms import modelformset_factory
from django.shortcuts import get_object_or_404, render
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

from .forms import ItemForm
from .models import Item, ItemImage, Sale


def index(request):
    return render(request, 'sales/index.html', {})


class SaleCreateView(CreateView):
    model = Sale
    fields = ['name']

class SaleManageView(DetailView):
    model = Sale
    template_name = 'sales/sale_manage.html'


class SaleUpdateView(UpdateView):
    model = Sale
    fields = ['name']


class SaleDeleteView(DeleteView):
    model = Sale
    success_url = reverse_lazy('sales:index')


class SaleDetailView(DetailView):
    model = Sale

class ItemManageView(DetailView):
    model = Item
    template_name = 'sales/item_manage.html'

class ItemSaleMixin:
    """Adds access to `Item` instance's `Sale` relation."""

    def get_success_url(self) -> str:
        """Redirect to related `Sale` instance's update page."""
        pk = self._get_sale_pk()
        return reverse_lazy('sales:sale-manage', kwargs={'pk': pk})

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        pk = self._get_sale_pk()
        context['sale_id'] = pk
        context['sale_name'] = Sale.objects.get(pk=pk)
        return context


class ItemCreateView(ItemSaleMixin, CreateView):
    model = Item
    fields = ['name', 'price', 'description']

    def dispatch(self, request, *args, **kwargs):
        """Overriden to make sure that `Sale` instance exists."""
        self.sale = get_object_or_404(Sale, pk=kwargs['sale_id'])
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        """Overriden to add the sale relation to the `Item` instance."""
        form.instance.sale = self.sale
        return super().form_valid(form)

    def _get_sale_pk(self):
        """Use saved `Sale` instance's `pk`."""
        return self.sale.pk


class ItemUpdateView(ItemSaleMixin, UpdateView):
    model = Item
    fields = ['name', 'price', 'description']

    def _get_sale_pk(self):
        """Use `Item` instance's related `Sale` instance for `pk`."""
        return self.get_object().sale.pk

    def get_success_url(self) -> str:
        """Redirect to related `Item` instance's update page."""
        pk = self.get_object().pk
        return reverse_lazy('sales:item-manage', kwargs={'pk': pk})


class ItemDeleteView(ItemSaleMixin, DeleteView):
    model = Item

    def _get_sale_pk(self):
        """Use `Item` instance's related `Sale` instance for `pk`."""
        return self.get_object().sale.pk


class ItemDetailView(DetailView):
    model = Item


class ItemMixin:
    """Adds access to `ItemImage` instance's `Item` relation."""

    def get_success_url(self) -> str:
        """Redirect to related `Item` instance's update page."""
        pk = self._get_item_pk()
        return reverse_lazy('sales:item-manage', kwargs={'pk': pk})

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['item_id'] = self._get_item_pk()
        return context


class ItemImageCreateView(ItemMixin, CreateView):
    model = ItemImage
    fields = ['image']

    def dispatch(self, request, *args, **kwargs):
        """Overriden to make sure that `Item` instance exists."""
        self.item = get_object_or_404(Item, pk=kwargs['item_id'])
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        """Overriden to add the item relation to the `ItemImage` instance."""
        form.instance.item = self.item
        return super().form_valid(form)

    def _get_item_pk(self):
        """Use saved `Item` instance's `pk`."""
        return self.item.pk


class ItemImageUpdateView(ItemMixin, UpdateView):
    model = ItemImage
    fields = ['image', 'primary']

    def _get_item_pk(self):
        """Use `ItemImage` instance's related `Image` instance for `pk`."""
        return self.get_object().item.pk


class ItemImageDeleteView(ItemMixin, DeleteView):
    model = ItemImage

    def _get_item_pk(self):
        """Use `ItemImage` instance's related `Item` instance for `pk`."""
        return self.get_object().item.pk

sales/templates/sales/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'sales/style.css' %}">

    <title>{% block title %}Hello, world!{% endblock %}</title>
  </head>
  <body>
    <header>
      <!-- Navigation -->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'sales:index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'sales:sale-create' %}">Add Sale<span class="sr-only">(current)</span></a>
            </li>
          </ul>
        </div>
      </nav>
      <h1 class="mx-2">{% block header %}{% endblock %}</h1>
    </header>

    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

sales/templates/sales/index.html
{% extends "sales/base.html" %}

{% block title %}Home{% endblock %}

{% block header %}Private Sales{% endblock %}

{% block content %}
<p>
  Welcome to the Private Sales app!
  You can create sales and share a public link to them without creating an account.
</p>
<p>
  Make sure to <strong>only</strong> share the public sales page with others. Do <strong>not</strong>
  share the url to any of the sale management pages. This would allow others to edit your, sales, items, and images and even <span class="text-danger">delete</span> them!
</p>
<p>
  To get started, <a href="{% url 'sales:sale-create' %}">add your first sale</a>.
</p>
{% endblock %}

sales/templates/sales/item_confirm_delete.html
{% extends "sales/base.html" %}

{% load crispy_forms_tags %}

{% block title %}
{# Change title based on whether model exists already #}
{% if item.pk %}Update{% else %}Create{% endif %} Item
{% endblock %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete {{ item.name }}?</p>

  <a href="{% url 'sales:item-manage' item.pk %}" class="btn btn-primary">Back</a>
  <button type="submit" class="btn btn-danger">Delete</button>
</form>
{% endblock %}

sales/templates/sales/item_detail.html
{% extends "sales/base.html" %}

{% load thumbnail %}

{% block title %}{{ item.name }}{% endblock %}

{% block header %}<a href="{% url 'sales:sale-detail' item.sale.slug %}">{{ item.sale.name }}</a> > {{ item.name }} <span class="text-muted">(${{ item.price }})</span>{% endblock %}

{% block content %}

<div class="card-deck text-center mx-2" style="max-width: 60rem;">

    <div class="card mx-auto w-75" style="max-width: 18rem;">
        <div class="card-header">Description</div>
        <div class="card-body text-left"><p>{{ item.description }}</p></div>
    </div>

    <div class="card mx-auto w-75" style="max-width: 40rem;">
        <div class="card-header">Images</div>
        <div class="card-body text-left">
            {% if item.images.exists %}
            {% for image in item.images.all %}
            {% thumbnail image.image "200x200" crop="center" as im %}
            <img class="rounded mx-auto m-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
            {% endthumbnail %}
            {% endfor %}
            {% else %}
            <p>This item does not have any images.</p>
            {% endif %}
        </div>
    </div>

</div>


{% endblock %}

sales/templates/sales/item_form.html
{% extends "sales/base.html" %}

{% load crispy_forms_tags %}

{% block title %}{% if item.pk %}Update{% else %}Create{% endif %} Item{% endblock %}

{% block header %}
  <a href="{% url 'sales:sale-manage' sale_id %}">{{ sale_name }}</a> > {% if item.pk %}Update{% else %}Create{% endif %} Item
{% endblock %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}

  <button type="submit" class="btn btn-primary">
    {% if item.pk %}Update{% else %}Create{% endif %}
  </button>
</form>
{% endblock %}

sales/templates/sales/item_manage.html
{% extends "sales/base.html" %}

{% load thumbnail %}

{% block title %}Manage {{ item.name }}{% endblock %}

{% block header %}
    <a href="{% url 'sales:sale-manage' item.sale.pk %}">{{ item.sale.name }}</a> > {{ item.name }}
{% endblock %}

{% block content %}
<div class="card-deck text-center mx-2" style="max-width: 60rem;">

    <div class="card mx-auto w-75" style="max-width: 18rem;">
        <div class="card-header">Sharing</div>
        <div class="card-body">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a href="{% url 'sales:item-detail' item.slug %}">View Item</a>
                </li>
                <li class="list-group-item">
                    <p>
                        Share the page url for <strong>View Item</strong> with others. Do <strong>not</strong> share the url in the browser bar above!
                    </p>
                    <p>
                        The <strong>View Item</strong> page does not give
                        access for editing and deleting, whereas this page does.
                    </p>
                </li>
            </ul>
        </div>
    </div>

    <div class="card mx-auto w-75" style="max-width: 18rem;">
        <div class="card-header">
            Manage Item
        </div>
        <div class="card-body">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a href="{% url 'sales:item-update' item.pk %}">Update</a>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'sales:item-delete' item.pk %}" class="text-danger">Delete</a>
                </li>
            </ul>
        </div>
    </div>

    <div class="card mx-auto w-75" style="max-width: 40rem;">
        <div class="card-header">Images</div>
        <div class="card-body">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a class="text-success" href="{% url 'sales:image-create' item.pk %}">Add Image</a>
                </li>
            {% for image in item.images.all %}
                <li class="list-group-item">
                    {% thumbnail image.image "200x200" crop="center" as im %}
                    
                    <img class="rounded mx-auto m-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                    {% endthumbnail %}
                    <a class="btn btn-danger" href="{% url 'sales:image-delete' image.pk %}">Delete</a>
                </li>
            
            {% endfor %}
            </ul>
        </div>
    </div>

</div>
{% endblock %}

sales/templates/sales/itemimage_confirm_delete.html
{% extends "sales/base.html" %}

{% load thumbnail %}

{% load crispy_forms_tags %}

{% block title %}Delete Image{% endblock %}

{% block content %}
<form method="post">
  {% csrf_token %}


  {% thumbnail itemimage.image "200x200" crop="center" as im %}
  <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
  {% endthumbnail %}

  <p>Are you sure you want to delete image?</p>

  <a href="{% url 'sales:item-manage' item_id %}" class="btn btn-primary">Back</a>
  <button type="submit" class="btn btn-danger">Delete</button>
</form>
{% endblock %}

sales/templates/sales/itemimage_form.html
{% extends "sales/base.html" %}

{% load crispy_forms_tags %}

{% block title %}{% if itemimage.pk %}Update{% else %}Create{% endif %} Image{% endblock %}

{% block content %}
<div class="card mx-auto" style="width: 30rem;">
  <div class="card-header">
    {% if itemimage.pk %}Update{% else %}Create{% endif %} Image
  </div>
  <div class="card-body">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}

      <a class="btn btn-secondary" href="{% url 'sales:item-update' item_id %}">Back</a>
      <button type="submit" class="btn btn-primary">{% if itemimage.pk %}Update{% else %}Create{% endif %}</button>
      {# delete #}
      {% if itemimage.pk %}
      <a href="{% url 'sales:image-delete' itemimage.pk %}" class="btn btn-danger">Delete</a>
      {% endif %}
    </form>
  </div>
</div>
{% endblock %}

sales/templates/sales/sale_confirm_delete.html
{% extends "sales/base.html" %}

{% block title %}Confirm Delete{% endblock %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <p>Are you sure you'd like to delete <em>{{ sale.name }}?</em></p>
  <a href="{% url 'sales:sale-update' sale.pk %}" class="btn btn-primary">No</a>
  <button type="submit" class="btn btn-danger">Yes</button>
{% endblock %}

sales/templates/sales/sale_detail.html
{% extends "sales/base.html" %}

{% block title %}{{ sale.name }}{% endblock %}

{% block header %}{{ sale.name }}{% endblock %}

{% block content %}

<div class="card-deck text-center mx-2" style="max-width: 60rem;">
  <div class="card mx-auto w-75" style="max-width: 18rem;">
    <div class="card-header">Items</div>
    <div class="card-body">
      {% if sale.items.exists %}
      <ul class="list-group list-group-flush">
        {% for item in sale.items.all %}
        <li class="list-group-item">
          <a href="{% url 'sales:item-detail' item.slug %}">{{ item.name }}</a> <span class="text-muted">(${{ item.price }})</span>
        </li>
        {% endfor %}
      </ul>
      {% else %}
      <p>There are no items in this sale yet.</p>
      {% endif %}
    </div>
  </div>
</div>


{% endblock %}

sales/templates/sales/sale_form.html
{% extends "sales/base.html" %}

{% load crispy_forms_tags %}

{% block title %}{% if sale.pk %}Update{% else %}Create{% endif %} Sale{% endblock %}

{% block header %}{% if sale.pk %}Update{% else %}Create{% endif %} Sale{% endblock %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <br>
  <button type="submit" class="btn btn-{% if sale.pk %}primary{% else %}success{% endif %}">
    {% if sale.pk %}Update{% else %}Create{% endif %}
  </button>
  {# add "delete" and "add item" if model exists already #}
  {% if sale.pk %}
  <a href="{% url 'sales:sale-delete' sale.pk %}" class="btn btn-danger">Delete</a>
  {% endif %}
</form>
{% endblock %}

sales/templates/sales/sale_manage.html
{% extends "sales/base.html" %}

{% block title %}Manage {{ sale.name }}{% endblock %}

{% block header %}{{ sale.name }}{% endblock %}

{% block content %}


<div class="card-deck text-center mx-2" style="max-width: 60rem;">
    <div class="card mx-auto w-75" style="max-width: 18rem;">
        <div class="card-header">Sharing</div>
        <div class="card-body">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a href="{% url 'sales:sale-detail' sale.slug %}">View Sale</a>
                </li>
                <li class="list-group-item">
                    <p>
                        Share the page url for <strong>View Sale</strong> with others. Do <strong>not</strong> share the url in the browser bar above!
                    </p>
                    <p>
                        The <strong>View Sale</strong> page does not give
                        access for editing and deleting, whereas this page does.
                    </p>
                    <p>
                        Make sure to save a copy of the url in the browser bar for this page for future editing.
                    </p>
                </li>
            </ul>
        </div>
    </div>

    <div class="card mx-auto w-75" style="max-width: 18rem;">
        <div class="card-header">Manage Sale</div>
        <div class="card-body">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a href="{% url 'sales:sale-update' sale.pk %}">Update</a>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'sales:sale-delete' sale.pk %}" class="text-danger">Delete</a>
                </li>
            </ul>
        </div>
    </div>

    <div class="card mx-auto w-75" style="max-width: 18rem;">
        <div class="card-header">Manage Items</div>
        <div class="card-body">
            <p>Add new items or click on existing items to <span class="text-success">add photos</span>, update information, or delete item.</p>


            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a class="text-success" href="{% url 'sales:item-create' sale.pk %}">Add Item</a>
                </li>

                {% for item in sale.items.all %}
                <li class="list-group-item">
                    <a href="{% url 'sales:item-manage' item.pk %}">{{ item.name }}</a> <span class="text-muted">(${{ item.price }})</span>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

</div>
{% endblock %}